id: A4B1B2949
title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching from
  the Lama Sangdü'
type: translation
pechas:
- IA6B6908B
- I400EF701
- I4CF0CD9B
- IFD1A4DD5
- I01476730
- IEE7D4FB0
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:58:00.207874
  last_modified_at: 2023-01-04 11:58:00.207879
  collections:
  - Guru Chökyi Wangchuk
  - Works of Tibetan Masters
alignment_to_base:
  IA6B6908B/B9AD: D295
  I400EF701/6FBD: D295
  I4CF0CD9B/465A: D295
  IFD1A4DD5/4117: D295
  I01476730/DB4E: D295
  IEE7D4FB0/8C94: D295
